apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: builders-test-1-hpa
  labels:
    app: builders-test-1
    version: 0.0.1
    backstage.io/kubernetes-id: builders-test-1
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: builders-test-1
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75